### PR TITLE
configures new disk sizes for k8s-kvm

### PR DESCRIPTION
**Pull request by xh3b4sd**
This is a first attempt. Code only. Need to test. Please provide feedback where things might be wrong or missing.

### CODE REVIEW

**Review by calvix — COMMENTED** [review]
from first look this looks good

**Review by tuommaki — APPROVED** [review]
LGTM

**Comment by calvix** [comment]
Lets try e2e and see.

**Comment by xh3b4sd** [comment]
Successfully tested on `geckon`. Tenant cluster `kg8mb` still there.

**Review by rossf7 — APPROVED** [review]
LGTM

**Review by calvix — APPROVED** [review]

**Comment by xh3b4sd** [comment]
Testing is blocked due to https://github.com/giantswarm/giantswarm/issues/4158.

**Pull request merged**
