### PR TITLE
Adding configmap and cloudconfig v3

### PR DESCRIPTION
**Pull request by jgsqware**
In order to add new version in kvm-operator, this PR start the work by duplicating the cloudconfig and config map

### CODE REVIEW

**Comment by xh3b4sd** [comment]
The CI does not build. Would be cool to sort this before asking for review. 

There was a workflow established that makes reviewing the evolution of packages more easy. The first PR you can do is just copying the existing package that you want to evolve. When you have `cloudconfigv2` you just copy to `cloudconfigv3` and that is your first PR. Because it is only the copy and nothing changes you can just ping people and go ahead like on vendor updates. The next PR would be to apply the actual changes to `cloudconfigv3`. Then we really see what changes and how the package develops in the next version. Right now I do not see what really changes because there is just a lot of code and at this point it could just be everything.

**Comment by jgsqware** [comment]
Local build was misconfigured sorry for that.

Here there is no code change, only duplication on both configmap and cloudconfig

You had prefer to get 1 PR for configmap and 1 for cloudconfig?

**Comment by xh3b4sd** [comment]
I don't think this is only the copy because the package imports changed as well. So you did more than just `cp foo bar`. I don't know what else changed. When you say nothing else changed I take you by the word. Then just go ahead.

**Comment by xh3b4sd** [comment]
I see also import paths changed. I would like to stick to the process as I described above, because at this point it looks like what you say does not reflect with what happened.

**Comment by jgsqware** [comment]
I don't get it. Import path are move accordingly to new folder, without doing this it even not compile 

which file/line are confusing you?

**Comment by xh3b4sd** [comment]
It is not possible for the reviewer to see what changed. So please create a pull request where you just copy files. You do not need to fix any imports or package names or whatever. The code you copied is not used for anything, so the code will still compile, because it is only copied, but not imported. Such copy PRs can be treaded like vendor PRs then. you can simply ping people and merge right away. The next PR from there can then be used to fix package names and import paths and whatever you like. Using this process it is easier for the reviewer to comprehend what really happened. This is just to keep the project reliably maintainable while packages are evolving.

**Comment by jgsqware** [comment]
ok got it and add some though on this on slack.

**Comment by jgsqware** [comment]
@xh3b4sd here it is

**Comment by jgsqware** [comment]
you mean here I ping you and merge it?

**Comment by xh3b4sd** [comment]
When this is just a copy and no other changes happened then you can go ahead IMO.

**Pull request merged**
