### PR TITLE
add v23patch1 to version bundles

### PR DESCRIPTION
**Pull request by cornelius-keller**
add v23patch1 to version bundles

### CODE REVIEW

**Comment by mazzy89** [comment]
Could you amend the git commit? it reports v23patch2.

**Comment by mazzy89** [comment]
Still missing different thing. I'll point here to some other PR to compare

**Comment by mazzy89** [comment]
https://github.com/giantswarm/kvm-operator/commit/15a06067ce5c1350f0c62207fcb404716ed31d76

**Comment by cornelius-keller** [comment]
Yes i had a typo in commit message. Fixed it.

**Comment by cornelius-keller** [comment]
@mazzy89 I think I was looking at an incomplete branch that I still had locally on the azure operator.
Will follow your reference.

**Comment by mazzy89** [comment]
Easy one 

```
./service/controller/v23patch1/version_bundle.go:11:24: missing ',' before newline in composite literal

```

maybe it would be better @cornelius-keller to install in your IDE the go-tool which when you save the files automatically format correctly them

**Pull request merged**
