### PR TITLE
creating v23patch1

### PR DESCRIPTION
**Pull request by cornelius-keller**
@mazzy89 @schjan not really sure if it is correct but I tried to follow the pattern I have seen in azure opperator.

### CODE REVIEW

**Comment by schjan** [comment]
I think you shoud base on `v23`

**Comment by mazzy89** [comment]
yes. confirm that. `v23patch1`

**Comment by cornelius-keller** [comment]
Okay. Will redo and force push.

**Comment by cornelius-keller** [comment]
or should I just delete this branch and open a new pr to have proper naming? Maybe this is better?

**Comment by mazzy89** [comment]
yes mauybe it is better. renamethe branch

**Comment by schjan** [comment]
I would not care that much about the branch, at it is gone after the merge. The important part which could lead to confusion is the name of the PR which I changed accordingly.

**Pull request closed without merging**
