### PR TITLE
test-k8scc-v-4-2-0

### PR DESCRIPTION
**Pull request by calvix**

### CODE REVIEW

**Comment by mazzy89** [comment]
I'm taking over this PR because we need to release k8s 1.14 which need k8scc 4.3.0. Hence this PR must be kicked in in order to move on.

**Comment by mazzy89** [comment]
I'm not going to move further with it because after a discussion with @teemow we found out that it could be left for later

**Comment by calvix** [comment]
This PR was from hackaton where i was testing a calico-typha as CNI, i would definitely drop this PR and create a new one with clean stuff, as this  have calico-typha related options in it

**Comment by xh3b4sd** [comment]
Can this be closed?

**Pull request closed without merging**
