### PR TITLE
Use helmclient for setup

### PR DESCRIPTION
**Pull request by MarcelMue**

### CODE REVIEW

**Comment by MarcelMue** [comment]
cc @kopiczko these are the changes I made now, going to check if it works next.

**Comment by MarcelMue** [comment]
Agreed, there is this issue:
https://github.com/giantswarm/giantswarm/issues/3878

I want to have some kind of `framework.go` which will handle all the config madness for clients and so on. I think that would be practical.

We might then also be able to shrink e2esetup libs to just the most important differences.

**Comment by xh3b4sd** [comment]
There happened a lot of work towards this already. This PR might be outdated.

**Comment by xh3b4sd** [comment]
I take over here and redo. Too outdated. Too many conflicts.

**Pull request closed without merging**
