### PR TITLE
Align rbac rules with other operators

### PR DESCRIPTION
**Pull request by MarcelMue**
There was no `kvmconfigs/status` at all in our rules here. We use the status resource here though, so how this works currently is a big :question: to me.

### CODE REVIEW

**Review by xh3b4sd — APPROVED** [review]
I cannot say much about how or why it currently works on the KVM envs. Maybe there is some k8s weirdness or configuration missing. Uncertain.

**Comment by xh3b4sd** [comment]
We have https://github.com/giantswarm/giantswarm/issues/4246 now. Lets get this done maybe.

**Review by r7vme — APPROVED** [review]

**Comment by xh3b4sd** [comment]
Can we merge this?

**Comment by pipo02mix** [comment]
IIRC if you allow the parent path resource ('kvmconfig') it means child path resources is allowed. Like 'logs' works for 'pod' resource read role

**Review by tuommaki — APPROVED** [review]
LGTM. Remember to test :slightly_smiling_face:

**Comment by tuommaki** [comment]
Oh and yeah, I think things work because I'm not sure if we use status specific API functions yet anywhere (because it's not long time ago since we still had to be compliant with pre-1.10 k8s) but just update the status field as part of the parent CR.

**Comment by xh3b4sd** [comment]
We use the `statusresurce` here so this should not be possible in case the rules aren't right.

**Comment by xh3b4sd** [comment]
Given the e2e tests are green and we got approvals already I merge this now.

**Pull request merged**
