### PR TITLE
tmp-fix-calico-proxy-kill

### PR DESCRIPTION
**Pull request by calvix**
tested on KVM lycan and seems to do the job properly.

Basically, it waits for healthy api and after that, it kills calico-node pods and 1 minute later kube-proxy.

### CODE REVIEW

**Comment by calvix** [comment]
Maybe if you have some time, test it yourself so we are 100% sure everything is OK.

**Comment by r7vme** [comment]
Probably makes sense to test by someone else, righ :D we are on our way to improve quality that will lead to stability.

I'll do that on Monday.

**Comment by r7vme** [comment]
works fine for me.

**Comment by calvix** [comment]
closed in favor of https://github.com/giantswarm/kvm-operator/pull/288

because of k8scloudconfig changes and merge conflict

**Comment by corest** [comment]
@calvix delete the branch?

**Comment by calvix** [comment]
yep, somehow missed that

**Pull request closed without merging**
