### PR TITLE
Use dns addresses for networkd configuration

### PR DESCRIPTION
**Pull request by corest**
Required for this https://github.com/giantswarm/k8s-kvm/pull/28

### CODE REVIEW

**Review by xh3b4sd — APPROVED** [review]
That should do it in general. I was just wondering about the consistency. This here is so consistent and is weird because the `kvm-operator` is anyway about the `kvm` provider.

**Comment by corest** [comment]
It is specific for onprem as we are configuring static networking for qemu node, which is unable to retrieve configuration with ignition and dhcp. Added configuration (https://github.com/giantswarm/installations/blob/master/geckon/draughtsman-configmap-values.yaml#L36) doesn't even exist for cloud providers

**Comment by xh3b4sd** [comment]
The installations repo is fine. There we need the distinction. Here we are in the `kvm-operator`. The operator having a flag ala `provider.kvm` is funny, because it is the `kvm-operator`. That is what I meant.

**Comment by corest** [comment]
Ah, got it. Just tried to keep configuration consistent with installation structure. But that is a questionable approach. Dropped `Provider.KVM` part

**Pull request merged**
