### PR TITLE
Flatcar stable

### PR DESCRIPTION
**Pull request by mazzy89**
https://github.com/giantswarm/giantswarm/issues/8553

See also https://github.com/giantswarm/k8s-kvm/pull/40

### CODE REVIEW

**Comment by mazzy89** [comment]
Pods partly up. KVM health check keeps failing

```
worker-mngh8-5d8d75fb5-mxn4v k8s-kvm-health {"caller":"github.com/giantswarm/k8s-kvm-health/vendor/github.com/giantswarm/microendpoint/endpoint/healthz/endpoint.go:92","error":"health check failed","healthCheckDescription":"Ensure KVM is responding to the assigned ip.","healthCheckMessage":"Healthcheck for KVM has failed. KVM is not responding on  172.23.3.14.","time":"2020-02-14T10:26:49.691881+00:00"}
```
need to debug why

**Comment by mazzy89** [comment]
@MarcelMue I deploy this branch

```
opsctl deploy -m app -i gorgoth --jumphost-user salvo kvm-operator@flatcar
```

then I create the clsuter with

```
gsctl create cluster -o giantswarm -n "SALVO_SRE_FLARCAR" -r 11.1.1
```

However the clsuter is created with CoreOS this because the k8s-kvm image sha is wrong and not the one from this PR.

**Comment by MarcelMue** [comment]
The deploy command is correct - no need for `app` though:
```
opsctl deploy  -i gorgoth --jumphost-user salvo kvm-operator@flatcar
```
Important is that your branch is using this `kvm-operator` version:
https://github.com/giantswarm/kvm-operator/blob/d27c3c1f4fa7f05e5ac22bd8078e120bc6ecd720/pkg/project/project.go#L4

This version `3.11.0-dev` needs to be in the `releases` yaml in your cluster.
To make this happen right now (because some teams are currently creating a new release for kvm) you can create a small PR to `releases` for `kvm-operator` and change the version in there to be `3.11.0-dev`. Tim has done something similar for aws here:
https://github.com/giantswarm/releases/pull/124/files

Then you do
```
opsctl update draughtsman --user salvo --no-cache -e salvo-releases-branch -i geckon
opsctl deploy cluster-service -i geckon
```
And then do:
```
opsctl deploy  -i geckon --jumphost-user salvo kvm-operator@flatcar
```

This is a bit more complicated right now unfortunately :(

**Comment by MarcelMue** [comment]
A very quick / dirty way to do it:
Do
```
opsctl deploy  -i gorgoth --jumphost-user salvo kvm-operator@flatcar
```
Create a cluster
Edit the version label on the`kvmConfig` to be `3.11.0-dev` and your operator should reconcile it.

**Comment by mazzy89** [comment]
So created a branch here https://github.com/giantswarm/releases/pull/125 
checked that my PR has `3.11.0-dev`. Run
```
➜ opsctl update draughtsman  -i gorgoth --user salvo --no-cache -e flatcar-kvm-operator
Updating draughtsman's configuration on gorgoth
Created draughtsman's config and secret files for gorgoth in temporary dir /var/folders/2g/_1jxp8dd60sf6m7xxtvhcjcm0000gn/T/opsctl-create-draughtsman172583342.
Applied draughtsman config and secret to gorgoth.

Creating deployment event
Created deployment event

    repository      draughtsman
    branch          master
    commit          bb799c631f8d725c5df104584c8df05422413532
    installation    gorgoth

Temporary dir /var/folders/2g/_1jxp8dd60sf6m7xxtvhcjcm0000gn/T/opsctl-create-draughtsman172583342 removed.
```

but `cluster-service` fails

**Comment by mazzy89** [comment]
The reason of this failure should be related that my PR into `releases` lack of `apps` block in the YAML file

**Comment by mazzy89** [comment]
deploye correctly cluster-service and release 11.3.0 appearing correctly. going to create a cluster and see if it works.

**Comment by mazzy89** [comment]
Moving to Flatcar Inignition does not run


```
➜ [57;162R[1]: Started Root filesystem setup.
  [   55.843257] systemd[1]: Starting Ignition (files)...
  [   55.855958] ignition[443]: Ignition v0.34.0-4-gd76e339
  [   55.861103] ignition[443]: Stage: files
  [   55.864853] ignition[443]: reading system config file "/usr/lib/ignition/base.ign"
  [   55.871714] ignition[443]: no config at "/usr/lib/ignition/base.ign"
  [   55.877579] ignition[443]: no config URL provided
  [   55.883345] ignition[443]: reading system config file "/usr/lib/ignition/user.ign"
  [   55.890986] ignition[443]: no config at "/usr/lib/ignition/user.ign"
  [   55.896839] ignition[443]: op(1): [started]  loading QEMU firmware config module
  [   55.903976] ignition[443]: op(1): [finished] loading QEMU firmware config module
```

**Comment by mazzy89** [comment]
Going to try with stable

**Comment by mazzy89** [comment]
@giantswarm/team-ludacris the good news is that *stable* works. *alpha* instead does not load correctly Ignition. I haven't tried *beta* though.

I haven't looked at the reason why it still does not work for `alpha`. I believe a newer Ignition version with some deviations. IIRC guys are going to deviate from CoreOS so this is expected.

```
NAME                            STATUS     ROLES    AGE   VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                                                 KERNEL-VERSION    CONTAINER-RUNTIME
master-yb94j-7f5fdf9468-wx6k4   NotReady   master   60s   v1.16.3   172.23.0.206   <none>        Flatcar Container Linux by Kinvolk 2303.4.0 (Rhyolite)   4.19.95-flatcar   docker://18.6.3
worker-ngfg9-56c5c75bf-gxjc4    NotReady   worker   49s   v1.16.3   172.23.0.174   <none>        Flatcar Container Linux by Kinvolk 2303.4.0 (Rhyolite)   4.19.95-flatcar   docker://18.6.3
```

**Comment by MarcelMue** [comment]
@mazzy89 `stable` working is good news. Please give the guys feedback that we can't get `alpha` to work. This is important because this is the only version with updated docker so far.

**Comment by mazzy89** [comment]
@MarcelMue I will check first if we need to make some changes from our side first. I believe that we might need it. For instance alpha runs with Ignition 0.34.0 while stable 0.33.0. This bump could make our Ignition version not compatible. I'm not new to the fact that bumping Ignition breaks the bootstrap of the machine. So this is expected.

**Comment by MarcelMue** [comment]
@mazzy89 Okay sounds like a good area to check - nice work!

**Comment by mazzy89** [comment]
And we have also **alpha** KMV with alpha running

```
NAME                            STATUS   ROLES    AGE   VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                                                 KERNEL-VERSION    CONTAINER-RUNTIME
master-scu8i-5c4dc74f9f-ptmn7   Ready    master   87s   v1.16.3   172.23.0.182   <none>        Flatcar Container Linux by Kinvolk 2387.0.0 (Rhyolite)   4.19.97-flatcar   docker://19.3.5
worker-9orxr-76774b5d74-d9fgw   Ready    worker   73s   v1.16.3   172.23.0.90    <none>        Flatcar Container Linux by Kinvolk 2387.0.0 (Rhyolite)   4.19.97-flatcar   docker://19.3.5
```

and docker 19.3.5 🔥

**Comment by MarcelMue** [comment]
> And we have also **alpha** KMV with alpha running
> 
> ```
> NAME                            STATUS   ROLES    AGE   VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                                                 KERNEL-VERSION    CONTAINER-RUNTIME
> master-scu8i-5c4dc74f9f-ptmn7   Ready    master   87s   v1.16.3   172.23.0.182   <none>        Flatcar Container Linux by Kinvolk 2387.0.0 (Rhyolite)   4.19.97-flatcar   docker://19.3.5
> worker-9orxr-76774b5d74-d9fgw   Ready    worker   73s   v1.16.3   172.23.0.90    <none>        Flatcar Container Linux by Kinvolk 2387.0.0 (Rhyolite)   4.19.97-flatcar   docker://19.3.5
> ```
> 
> and docker 19.3.5 fire

NICE :tada: 

What was the trick?

**Comment by mazzy89** [comment]
the newest alpha was simply broken. confirmed by Kinvolkg guys

**Comment by cornelius-keller** [comment]
cool! good news.

**Comment by mazzy89** [comment]
After a discussion with the team today, we decided to release KVM with Flatcar *stable*. Alpha has been tested too 2387.0.0 so when it will become stable, very likely end of this Q1 then we'll simply bump and make a quick release.

**Comment by mazzy89** [comment]
@giantswarm/team-ludacris IIRC we are going to release this with KVM 11.3.0 since 11.2.0 has been already out. right?

**Comment by tfussell** [comment]
Makes sense to me to release this as v11.3.0. it's even better if this can be the same version for all three providers so it's less confusing.

**Comment by mazzy89** [comment]
So this merged https://github.com/giantswarm/k8s-kvm/pull/40

agreed to release Flatcar in KVM 11.3.0. Do we need to make some changes here? Can we release this safely?

**Comment by mazzy89** [comment]
Also I remember that adidas wants to have Flatcar too so we need to release Flatcar for an older but still supported KVM version that is 9.1.0.

**Comment by omegas27** [comment]
Adidas is planning on upgrading to 9.2.0 so maybe we can just create a 9.3.0 release with flatcar?

**Comment by mazzy89** [comment]
Right so there is already a 9.2.0 released. so make sense 9.3.0

**Comment by MarcelMue** [comment]
Add changelogs here please - so it's one PR:
https://github.com/giantswarm/kvm-operator/blob/0cd4a8b241d63b34dd820383a2d78fb5f9c86f76/pkg/project/version_bundle.go#L9-L18

**Comment by mazzy89** [comment]
Added changelog. Last check before merging this.

**Pull request merged**
