### PR TITLE
Fixing import

### PR DESCRIPTION
**Pull request by tomahawk28**
According to our fmt, we should have `metav1` rather than `apiv1`. 
This PR fixes those on kvm-operator.

### CODE REVIEW

**Review by rossf7 — CHANGES_REQUESTED** [review]
Great to improve this but we should only change the WIP version. So when the code gets copied future versions have it. 

We should only backport changes to previous versions when we have to.

**Comment by tomahawk28** [comment]
@rossf7 I changed to v26 only in here PTAL.

**Review by MarcelMue — APPROVED** [review]
Looks fine from a quick skim. Please test.

**Review by rossf7 — APPROVED** [review]
LGTM when tested

**Comment by tomahawk28** [comment]
```  Warning  Unhealthy  52m (x7 over 56m)     kubelet, 10.0.4.103  Readiness probe failed: Get http://127.0.0.1:23012/healthz: dial tcp 127.0.0.1:23012: connect: connection refused
  Warning  Unhealthy  37m (x6 over 51m)     kubelet, 10.0.4.103  Liveness probe failed: HTTP probe failed with statuscode: 500
  Warning  Unhealthy  7m34s (x61 over 51m)  kubelet, 10.0.4.103  Readiness probe failed: HTTP probe failed with statuscode: 500``` geckon is flapping.

**Comment by rossf7** [comment]
> geckon is flapping.

Not sure. Maybe check in #ops if you think it's an issue with the control plane?

**Comment by tomahawk28** [comment]
Works well after restarting master pod 😁.

**Pull request merged**
