### PR TITLE
Remove CRD management

### PR DESCRIPTION
**Pull request by MarcelMue**
Do we also need to add something to opsctl or is this fine for now?

### CODE REVIEW

**Comment by MarcelMue** [comment]
@giantswarm/team-ludacris PTAL as I want to tag kvm-operator :D

**Comment by stone-z** [comment]
Should this also be removed elsewhere? e.g. flag, the helm configmap, and service.go?

**Comment by MarcelMue** [comment]
> Should this also be removed elsewhere? e.g. flag, the helm configmap, and service.go?

I don't think so - this should match the change @tfussell did on AWS operator.

**Comment by tfussell** [comment]
> Do we also need to add something to opsctl or is this fine for now?

Sorry for being slow looking at this. We'll depend on released operators to ensure the CRDs for now. Once we have migrated KVM CRDs to v1, we will uncomment it in `opsctl ensure crds`, then deploy our patched operators.

**Pull request merged**
