### PR TITLE
Bring k8s 1.11.1 into WIP release

### PR DESCRIPTION
**Pull request by corest**

### CODE REVIEW

**Review by xh3b4sd — APPROVED** [review]
Looks good so far. Lets make sure the update from the former version works properly. In KVM we still do not have e2e tests for that.

**Review by kopiczko — APPROVED** [review]

**Review by MarcelMue — APPROVED** [review]

**Comment by corest** [comment]
Tested upgrade manually, works fine

**Comment by xh3b4sd** [comment]
Didn't you find issues? There as some Slack discussion.

**Comment by corest** [comment]
Well, eventually it worked, but will postpone before testing other operators

**Comment by xh3b4sd** [comment]
Can you create an issue though to make sure we check back on the problems you perceived?

**Pull request merged**
