### PR TITLE
adjust-memory-formula

### PR DESCRIPTION
**Pull request by calvix**
adjusting memory formula for https://github.com/giantswarm/giantswarm/issues/4300

from `2 + x/12`
to `1 + x/15 +x/25 +x/50 +x/100`

Also now are the limits more progressive depending on the Mem value instead of having jumps after 12G.

### CODE REVIEW

**Comment by JosephSalisbury** [comment]
Do we have observability between the amount of memory a worker is using, and the amount of overhead we give?

**Comment by xh3b4sd** [comment]
Having metrics and a dashboard for these things would be really really good.

**Review by r7vme — APPROVED** [review]
<3

**Comment by calvix** [comment]
There seem to be some dashboards in grafana for KVM clusters but no graph for memory eating versus memory limit.

**Comment by xh3b4sd** [comment]
Yeah so we could emit a metric for the calculated available overhead. We should have metrics about the currently used memory already.

**Comment by calvix** [comment]
I wonder if we need another metric.
We have metrics for current memory usage and we  have metrics for the resource limit so we can have a graph, where we see how close is the mem, to reach the limit so we can see if its working or if i too low or too high.

**Comment by calvix** [comment]
I have created new dashboard to see memory usage and memory limit for KVM worker pods https://github.com/giantswarm/g8s-grafana/pull/92

**Review by tuommaki — APPROVED** [review]
LGTM

**Comment by calvix** [comment]
Last question: should this be included in all previous version or are we fine with having this fix only for this and future.

**Comment by xh3b4sd** [comment]
I am fine with having it in the latest version. When we backport we will not change anything anyway in the running pods I guess.

**Comment by calvix** [comment]
Yeah true. we will need to update anyway.

**Pull request merged**
