### PR TITLE
update-node-controller-image-bugfix

### PR DESCRIPTION
**Pull request by calvix**
towards issue: https://github.com/giantswarm/adidas/issues/253
changes in node controller: https://github.com/giantswarm/kvm-operator-node-controller/issues/12

this bugfix is backported to all releases

### CODE REVIEW

**Comment by r7vme** [comment]
@xh3b4sd what are your thoughts about this?

**Comment by calvix** [comment]
this doesn't not influence version bundles

**Comment by xh3b4sd** [comment]
> this doesn't not influence version bundles

Why not? We should definitely create a new patch release and put the fix in there. We can only fix by moving forward. There is nothing like sneaking in fixes.

**Comment by calvix** [comment]
> Why not? We should definitely create a new patch release and put the fix in there. We can only fix by moving forward. There is nothing like sneaking in fixes.

This would work nicely in case we got updates in place.  But most of the current kvm clusters have version `""` and this is a quite critical bugfix that we need to implement ASAP, so creating a new patch is nice but if we cant apply it to current clusters its like we never did any fix.

**Comment by xh3b4sd** [comment]
I think whatever we hack here will not be applied anyway so how do you want to handle that? You would need to roll all guest clusters manually and I think we should just not do this. The incentive for the customer to roll to newer versions on their own should be there and if we are able to hack it somehow anyway they will never have a reason to move on their own.

**Comment by r7vme** [comment]
This may be can help. 

we have following version bundles:
- `0.1.0` - deprecated (kvmconfig v2)
- `1.0.0` - deprecated (kvmconfig v2)
- `1.1.0` - deprecated (kvmconfig v3)
- `1.2.0` - deprecated (kvmconfig v4)
- `2.0.0` (kvmconfig v5)


we have following versions of clusters
```
kvm-operator|master ⇒ context-use giantswarm-anubis                           
Switched to context "giantswarm-anubis".
kvm-operator|master ⇒ kubectl get kvmconfigs -o yaml | grep versionBundle -A 1
    versionBundle:
      version: 2.0.0
--
    versionBundle:
      version: ""
--
    versionBundle:
      version: 0.1.0
--
    versionBundle:
      version: 2.0.0
--
    versionBundle:
      version: ""
--
    versionBundle:
      version: ""
--
    versionBundle:
      version: 1.2.0
--
    versionBundle:
      version: ""
kvm-operator|master ⇒ context-use giantswarm-centaur                          
Switched to context "giantswarm-centaur".
kvm-operator|master ⇒ kubectl get kvmconfigs -o yaml | grep versionBundle -A 1
    versionBundle:
      version: 0.1.0
--
    versionBundle:
      version: ""
--
    versionBundle:
      version: ""
--
    versionBundle:
      version: 1.0.0
--
    versionBundle:
      version: ""
--
    versionBundle:
      version: ""
--
    versionBundle:
      version: ""
--
    versionBundle:
      version: ""
--
    versionBundle:
      version: ""
--
    versionBundle:
      version: ""
kvm-operator|master ⇒ context-use giantswarm-amagon                           
Switched to context "giantswarm-amagon".
kvm-operator|master ⇒ kubectl get kvmconfigs -o yaml | grep versionBundle -A 1
    versionBundle:
      version: ""
--
    versionBundle:
      version: 0.1.0
--
    versionBundle:
      version: 1.0.0
```

**Comment by calvix** [comment]
manual fix it is then

**Pull request closed without merging**
