### PR TITLE
Fix service types

### PR DESCRIPTION
**Pull request by r7vme**
Fixes: https://github.com/giantswarm/kvm-operator/issues/500

### CODE REVIEW

**Comment by xh3b4sd** [comment]
The reason why we went with `ServiceTypeLoadBalancer` back then was that any other service type overwrites the endpoints and thus the IPs managed by the endpoint updater are purged resulting in the workloads being unavailable. Did you test this? Did the underlying k8s magic change? I am really not sure about this here.

**Comment by r7vme** [comment]
Good to know, i'll test this.

**Comment by xh3b4sd** [comment]
It would be pretty beneficial to have e2e tests for KVM. Is there maybe something we can do to get closer to this? We have these tests written already. It is just that we did not setup the infra accordingly and do not run them. That would be pretty sweet.

**Comment by r7vme** [comment]
Tested and added changelog.

**Comment by r7vme** [comment]
Pls review

**Review by corest — APPROVED** [review]
lgtmiwfy

**Review by calvix — COMMENTED** [review]
Did you also try to kill host api or worker/masters or/and endpoint/operator to ensure the right ip will stay there?

**Comment by r7vme** [comment]
> Did you also try to kill host api or worker/masters or/and endpoint/operator to ensure the right ip will stay there?

did not get sorry. In general, k8s documentations says [following](https://kubernetes.io/docs/concepts/services-networking/service/)

> Because this service has no selector, the corresponding Endpoints object will not be created. You can manually map the service to your own specific endpoints:

In other words, if there is a selector in service (which we don't have), then endpoints managed by k8s, if no selector (our case) then we can manage endpoints. So in general, nothing has been changed.

**Comment by xh3b4sd** [comment]
I still think we should write e2e tests for KVM with this now. We have to put the effort for testing with the stories we work on on a daily basis. You skip it now. The next one skips it tomorrow. Next week everybody is whining again why X and Y and Z is not working and how some incident could happen. We agreed on several times now that we want to write more and better e2e tests. So IMO this here is the perfect opportunity. We are also doing it in the scope of the update story. Like a lot. We are pushing hard there as well.

**Comment by xh3b4sd** [comment]
We had this and still have it on our list but KVM got rejected in terms of priority due to pushing Azure harder. You also do not have to do everything on your own. What I would need to push this more is to be able to add a test to the repo like we have them in the `aws-operator` and `azure-operator` already and when I push and approve the hold target then it is executed. The last bit "then it is executed" is unclear to me and I do not know how this works so I need help there. When you want to take this then cool.

**Comment by calvix** [comment]
no objections

**Review by kopiczko — APPROVED** [review]
When @r7vme tested that and is confident about the change LGTM.

I understand it would be nice to have e2etest, but we don't have infra set up. And as @r7vme said it isn't in our team scope. It shouldn't be a blocker for merging some boyscouting change.

**Comment by xh3b4sd** [comment]
Automating testing is not about a team scope but about the daily business of engineers. Everybody agreed on that in our QA session.

**Pull request merged**
