### PR TITLE
Update vendor [deny-all]

### PR DESCRIPTION
**Pull request by mazzy89**

### CODE REVIEW

**Comment by tfussell** [comment]
Looks good. Could you try creating a TC with this branch and report back how it works?

**Comment by mazzy89** [comment]
Already done. I've reported back in here https://github.com/giantswarm/k8scloudconfig/pull/609

**Comment by tfussell** [comment]
Okay, wasn't sure which operator that was for. All of the apps started up alright? Looks fine to me now then. Maybe just assign the issue to yourself and request review from sig-operator to keep everyone in the loop.

**Comment by mazzy89** [comment]
Sig operator don't think is the right group. SIG infra and SRE

**Comment by mazzy89** [comment]
>  All of the apps started up alright? 
Yep yep

**Comment by tfussell** [comment]
It has implications for all pods running our services on TCs so I just thinking some extra visibility is good. But I'm still not clear on exactly which topics should be reviewed by which SIGs. That makes sense.

**Review by tfussell — APPROVED** [review]
If our apps aren't affected and the cluster spins up fine, I say it's good.

**Comment by mazzy89** [comment]
assigned SIG operator here as well. considering the weekend is coming don't going to merge this now and leave space

**Review by corest — APPROVED** [review]
lgtm if tested

**Pull request merged**
