### PR TITLE
Release kvm-operator 2.2.0

### PR DESCRIPTION
**Pull request by corest**

### CODE REVIEW

**Review by xh3b4sd — COMMENTED** [review]
I would like to wait with this if nothing speaks against it to get my changes towards updates in here. If you have to go to fix something, go for it anyway.

**Comment by corest** [comment]
I need this https://github.com/giantswarm/k8scloudconfig/pull/355
I can wait, but then we will need to fix manually more cluster, which will be started this week

**Comment by xh3b4sd** [comment]
When you need it do not wait.

**Comment by xh3b4sd** [comment]
AFAIK this is about getting k8s `1.10.x`out right? We have a postmortem in which we noticed `1.10.x` introduces a regression. See https://github.com/giantswarm/giantswarm/issues/2999. So we should fix known bugs before releasing something that introduces bugs.

**Comment by r7vme** [comment]
@xh3b4sd i'm taking care on https://github.com/giantswarm/giantswarm/issues/2999 , because it's blocking me. We've already discussed this with @calvix .

@corest if you don't mind i'll go with https://github.com/giantswarm/kvm-operator/pull/471 . In your PR i don't see whole changelog from 3.2.5.

**Comment by xh3b4sd** [comment]
Can we close this?

**Comment by xh3b4sd** [comment]
I am closing this now. Seems to be irrelevant.

**Pull request closed without merging**
