### PR TITLE
service: freeze 1.2.0; deprecate 1.1.0

### PR DESCRIPTION
**Pull request by kopiczko**
I'll make announcement in #news-dev and merge on Monday if OK.

This is a minor bump, because of OS update.
This also fixes auditlog issue. Towards https://github.com/giantswarm/giantswarm/issues/2346

### CODE REVIEW

**Comment by xh3b4sd** [comment]
Is it now that you should also add another WIP bundle or does anybody who adds new stuff first has to do it?

**Comment by kopiczko** [comment]
I think we didn't agree on that. I can do either, but I think it would be nice to do it by a person who finalizes latest WIP (i.e. me in this case). Do you have thoughts on that?

**Comment by xh3b4sd** [comment]
I think when you freeze a WIP you should create a new one so others can just get started right away. But I am 50 50. Uncertain.

**Comment by calvix** [comment]
+1 for creating new WIP when closing previous one

**Pull request merged**
