### PR TITLE
Prepare helm for flat deployment

### PR DESCRIPTION
**Pull request by stone-z**

### CODE REVIEW

**Comment by tfussell** [comment]
Can we go ahead and rename `helm/kvm-operator-chart` to `helm/kvm-operator` here instead of creating a second parallel chart? Would be a little nicer to viewing differences, but I don't totally remember the process we used before.

**Comment by stone-z** [comment]
> Can we go ahead and rename `helm/kvm-operator-chart` to `helm/kvm-operator` here instead of creating a second parallel chart? Would be a little nicer to viewing differences, but I don't totally remember the process we used before.

Sure, I thought we needed both for e2e tests. Will update momentarily

**Comment by stone-z** [comment]
Will rename the folder back to `helm/kvm-operator` once the changes are approved

**Comment by tfussell** [comment]
> > Can we go ahead and rename `helm/kvm-operator-chart` to `helm/kvm-operator` here instead of creating a second parallel chart? Would be a little nicer to viewing differences, but I don't totally remember the process we used before.
> 
> Sure, I thought we needed both for e2e tests. Will update momentarily

I think you're right except we don't have e2e tests on this operator as far as I know.

**Pull request merged**
