### PR TITLE
Use Local as NGINX external traffic policy

### PR DESCRIPTION
**Pull request by sslavic**
Towards giantswarm/giantswarm#8877

### CODE REVIEW

**Comment by tfussell** [comment]
I'm going to try to simplify the required changes with this related PR https://github.com/giantswarm/kvm-operator/pull/946

**Comment by sslavic** [comment]
Thanks @tfussell !
Essentially need single line of code changed in k8scloudconfig https://github.com/giantswarm/k8scloudconfig/pull/709/files#diff-a75a3fdc88577edec2da9a96bd3d3b0dR28
and then have kvm-operator updated to use that k8scloudconfig, but all the pending updates got in the way.

**Comment by tfussell** [comment]
@sslavic You should be unblocked to make this code change now and once https://github.com/giantswarm/kvm-operator/pull/970 is released in kvm-operator@3.12.0 tomorrow you can create clusters to test it.

**Comment by tfussell** [comment]
This is pretty outdated now. Mind if we close it @sslavic?

**Pull request closed without merging**
