### PR TITLE
migrate-endpoint-updater-to-annotations

### PR DESCRIPTION
**Pull request by calvix**
parent story - https://github.com/giantswarm/giantswarm/issues/1972
* add changes related to new `endpoint-operator` and migration `k8s-endpoint-updater` to annotations
* cleaned some inconsistency between master and worker
* changes for https://github.com/giantswarm/k8s-endpoint-updater/pull/16

### CODE REVIEW

**Comment by calvix** [comment]
Yep :)

**Comment by calvix** [comment]
Should I also remove the k8s-endpoint-updater version from TPR and put it into operator?

**Comment by xh3b4sd** [comment]
> Should I also remove the k8s-endpoint-updater version from TPR and put it into operator?

I think it makes sense to do it this way from now on. I am only not sure if this specific task is important now. I would maybe try to focus on the versions that are user facing because these represent the components users will have control over.

**Comment by calvix** [comment]
I did some more changes in order to ENV value work. If you are not ok with the changes, ping me.

**Comment by xh3b4sd** [comment]
When this works lets roll.

**Pull request merged**
